### ISSUE TITLE
Error "FileNotFound", Python 3.5 on Windows and macOS 

### ISSUE THREAD

**Issue by bopmar** [paolodragone/pymzn#16]
Hi, 
I tried to launch a simple .py file like the example proposed, but i got this error on macOS High Sierra:
```
Traceback (most recent call last):
 File "/Users/Username/Desktop/Test.py", line 3, in <module>
  pymzn.minizinc("test.mzn", "test.dzn")
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymzn/mzn/minizinc.py", line 202, in minizinc output_mode=_output_mode)
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymzn/mzn/minizinc.py", line 308, in mzn2fzn run(args)
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-
packages/pymzn/mzn/utils.py", line 50, in run stderr=subprocess.PIPE) as process:
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py",
line 676, in __init__
  restore_signals, start_new_session)
 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py",
line 1289, in _execute_child
  raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: "mzn2fzn"
```

and this one on Windows 10

```
Traceback (most recent call last):
  File "C:/Users/Username/Desktop/pymzn/Test.py", line 3, in <module>
    pymzn.minizinc('test.mzn', 'test.dzn')
  File "C:\Program Files\Python35\lib\site-packages\pymzn\mzn\minizinc.py", line 202, in minizinc
    output_mode=_output_mode)
  File "C:\Program Files\Python35\lib\site-packages\pymzn\mzn\minizinc.py", line 308, in mzn2fzn
    run(args)
  File "C:\Program Files\Python35\lib\site-packages\pymzn\utils.py", line 50, in run
    stderr=subprocess.PIPE) as process:
  File "C:\Program Files\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
```

I've already installed MiniZinc. How can I solve this?

**Comment by paolodragone** [comment]
Hi,
looks like you haven't set your PATH variable correctly, you should add the path to your MiniZinc installation into your PATH environment variable. The previous method is recommended, but alternatively you can configure PyMzn like this:
`pymzn.config.set('mzn2fzn', 'path/to/mzn2fzn')`
On MacOS I am fairly positive it should work fine, but I never tested the library on Windows and other people have reported some problems, so use with care. I'll try to make it work on Windows in the near future!

**Comment by paolodragone** [comment]
I tested the latest release on Windows and seems to work fine now.
