### ISSUE TITLE
Can't convert int object to str implicitly

### ISSUE THREAD

**Issue by tomaszgy** [paolodragone/pymzn#5]
Hello,

I have been using your package recently (a nice one, btw 👍 ) and just discovered something that looks to like a tiny bug. While passing `timeout` to `pymzn.minizinc()` function with the default `gecode` solver, I get:

```
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main()
  File "main.py", line 36, in main
    run_test_cases()
  File "main.py", line 28, in run_test_cases
    schedule = run_solver(**test_case, debug=True)
  File "/Users/me/my_project/minizinc_service.py", line 74, in run_solver
    timeout=1000)
  File "/usr/local/lib/python3.5/site-packages/pymzn/_mzn/_minizinc.py", line 169, in minizinc
    all_solutions=all_solutions, **solver_args)
  File "/usr/local/lib/python3.5/site-packages/pymzn/_mzn/_solvers.py", line 212, in solve
    process = run(args)
  File "/usr/local/lib/python3.5/site-packages/pymzn/bin.py", line 105, in run
    preexec_fn=os.setsid) as process:
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'int' object to str implicitly
```

As it seemed like there was a typo [here](https://github.com/paolodragone/pymzn/blob/master/pymzn/_mzn/_solvers.py#L196), I did a quick fix, and tried it locally. It did the job for me so I'll leave a PR in few minutes in case you find it useful :) Cheers!

**Comment by paolodragone** [comment]
Thank you! :)

**Comment by tomaszgy** [comment]
No problem :)
