### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by jgjverheij** [paolodragone/pymzn#7]
Hi,

I was trying to run pymzn on my windows machine and it got stuck on a Linux command. This is the traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jver\AppData\Local\Programs\Python\Python35\lib\site-packages\pymzn\_mzn\_minizinc.py", line 161, in minizinc stdlib_dir=stdlib_dir)
  File "C:\Users\jver\AppData\Local\Programs\Python\Python35\lib\site-packages\pymzn\_mzn\_minizinc.py", line 295, in mzn2fzn run(args)
  File "C:\Users\jver\AppData\Local\Programs\Python\Python35\lib\site-packages\pymzn\bin.py", line 105, in run preexec_fn=os.setsid) as process:
AttributeError: module 'os' has no attribute 'setsid'
```

**Comment by jordicapde** [comment]
+1 to @jgjverheij's question. I have also got stuck at the same point

**Comment by alberthkcheng** [comment]
+1
really hope this awesome package would work in windows!

**Comment by paolodragone** [comment]
Latest release seems to work fine on Windows.
